# fly.toml app configuration file generated for trailfinder on 2023-12-25T09:41:04-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trailfinder"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
